// ==UserScript==
// @name         AutoBI 16.1.1.24
// @namespace    https://github.com/PhamngocNDH/AutoBI
// @version      16.1.1.24
// @description  AutoBI 16.1.1.24 - Trả chậm auto safe patch
// @author       38967 - Mr Phạm
// @match        https://baocao.dienmayxanh.com/*
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_deleteValue
// ==/UserScript==

(function(){
'use strict';
if(window.top!==window)return;
const DATA_KEY='tgdd_data_cache_v30',STATE_KEY='autobi_tc24_state',LAST_KEY='autobi_tc24_last_ok',DEBUG_KEY='autobi_tc24_debug',PATH_TC='/dashboard/tra-cham',REGION_CODE='761',AREA_CODE='3866',COOLDOWN=10*60*1000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),text=e=>(e?.innerText||e?.textContent||'').trim(),vis=e=>!!e&&!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length),num=v=>{const n=parseFloat(String(v??'').replace(/,/g,'').replace(/%/g,'').trim());return Number.isFinite(n)?n:0};
const gv=(k,d=null)=>{try{return GM_getValue(k,d)}catch(_){return d}},sv=(k,v)=>{try{GM_setValue(k,v)}catch(_){}},dv=k=>{try{GM_deleteValue(k)}catch(_){}},obj=v=>{if(typeof v==='string')try{v=JSON.parse(v)}catch(_){}return v&&typeof v==='object'?v:{}};
function toast(m,ms=3600){try{const w=typeof unsafeWindow!=='undefined'?unsafeWindow:window;if(w.UI?.showToast)return w.UI.showToast(m,ms)}catch(_){}console.log('[AutoBI 24]',m)}
function debug(step,extra=''){sv(DEBUG_KEY,{time:Date.now(),step,extra:String(extra||'')});console.log('[AutoBI 24]',step,extra)}
async function wait(fn,to=15000,step=250){const end=Date.now()+to;while(Date.now()<end){try{const v=fn();if(v)return v}catch(_){}await sleep(step)}return null}
function badge(){let b=document.getElementById('autobi-tc24-badge');if(b)return b;b=document.createElement('div');b.id='autobi-tc24-badge';b.style.cssText='position:fixed;right:16px;bottom:80px;z-index:2147483647;max-width:420px;padding:9px 12px;border-radius:9px;background:#e7f1ff;color:#084298;border:1px solid #b6d4fe;font:600 12px/1.45 Arial;box-shadow:0 3px 12px rgba(0,0,0,.18)';document.documentElement.appendChild(b);return b}
function status(s,ok=false){const b=badge();b.style.background=ok?'#d1e7dd':'#e7f1ff';b.style.color=ok?'#0f5132':'#084298';b.style.borderColor=ok?'#badbcc':'#b6d4fe';b.innerHTML=(ok?'✅ ':'⏳ ')+s;debug(s)}
function allAntSelects(){return[...document.querySelectorAll('.ant-select')].filter(vis)}
function findFilter(label){const q=norm(label),sels=allAntSelects();let hit=sels.find(s=>norm(text(s)).startsWith(q)||norm(text(s)).includes(q+' '));if(hit)return hit;const idx=q==='vung'?0:q==='khu vuc'?1:q==='sieu thi'?2:-1;return idx>=0?sels[idx]||null:null}
async function openFilter(label){const s=await wait(()=>findFilter(label),10000);if(!s)return null;try{(s.querySelector('.ant-select-selector')||s).click()}catch(_){return null}await sleep(350);return wait(()=>[...document.querySelectorAll('.ant-select-dropdown:not(.ant-select-dropdown-hidden)')].filter(vis).pop(),5000)}
function exactAction(root,label){const q=norm(label),els=[...root.querySelectorAll('button,a,label,span,div,li')].filter(vis);return els.find(e=>norm(text(e))===q)||els.find(e=>norm(text(e)).includes(q))||null}
function optionByCode(root,code,nameHint=''){const hint=norm(nameHint),els=[...root.querySelectorAll('label,li,[role="option"],div')].filter(vis);let r=els.find(e=>new RegExp('(^| )'+code+'( |$)').test(norm(text(e))));if(!r&&hint)r=els.find(e=>norm(text(e)).includes(hint));return r||null}
async function closeDrop(){try{document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))}catch(_){}await sleep(250)}
async function clearCurrent(root){const b=exactAction(root,'Bỏ chọn tất cả')||exactAction(root,'Bỏ chọn đang lọc');if(b){try{(b.closest('button,a,label')||b).click()}catch(_){}await sleep(350);return true}return false}
async function selectOne(label,code,hint){const d=await openFilter(label);if(!d)throw new Error('Không mở được bộ lọc '+label);await clearCurrent(d);const row=optionByCode(d,code,hint);if(!row)throw new Error('Không thấy '+label+' '+code);const cb=row.querySelector('input[type="checkbox"]');try{(cb||row.closest('label,li,[role="option"]')||row).click()}catch(_){throw new Error('Không click được '+label)}await sleep(500);await closeDrop();return true}
async function clearStores(){const d=await openFilter('Siêu thị');if(!d)throw new Error('Không mở được bộ lọc Siêu thị');let ok=await clearCurrent(d);if(!ok){const boxes=[...d.querySelectorAll('input[type="checkbox"]')];for(const cb of boxes)if(cb.checked){try{cb.click();await sleep(120)}catch(_){}}}await sleep(400);await closeDrop();return true}
function findButton(label){const q=norm(label);return[...document.querySelectorAll('button,a')].filter(vis).find(e=>norm(text(e))===q)||null}
async function clickXem(){const b=await wait(()=>findButton('Xem'),7000);if(!b)throw new Error('Không thấy nút Xem');b.click();await sleep(2200)}
function clickIfExists(label){const q=norm(label),e=[...document.querySelectorAll('button,a,span,div')].filter(vis).find(x=>norm(text(x))===q);if(e){try{(e.closest('button,a')||e).click();return true}catch(_){}}return false}
function classify(label){const s=norm(label);if(s.includes('hha')||s.includes('hai anh'))return'shop1';if(s.includes('tni')||s.includes('truc cuong'))return'shop2';return null}
function findStoreTable(){for(const t of document.querySelectorAll('table')){const h=norm(text(t.querySelector('thead'))||text(t));if(!h.includes('sieu thi')||!h.includes('dt tra gop')||!h.includes('dt sieu thi')||!h.includes('homecredit')||!h.includes('fecredit'))continue;let ha=false,tc=false;for(const tr of t.querySelectorAll('tbody tr')){const k=classify(text(tr.querySelector('td')));if(k==='shop1')ha=true;if(k==='shop2')tc=true}if(ha&&tc)return t}return null}
function parseRow(tr){const a=[...tr.querySelectorAll('td')];if(a.length<7)return null;const key=classify(text(a[0]));if(!key)return null;const r={key,label:text(a[0]),dtTraGop:num(text(a[1])),dtSieuThi:num(text(a[2])),tyTrong:num(text(a[3])),hc:num(text(a[4])),fe:num(text(a[6])),kredivo:a[8]?num(text(a[8])):0};if(!(r.dtSieuThi>0)||r.dtTraGop<0||r.tyTrong<0||r.tyTrong>100)return null;const calc=r.dtTraGop/r.dtSieuThi*100;if(Math.abs(calc-r.tyTrong)>1.25)return null;if(r.hc<0||r.fe<0||r.hc>r.dtTraGop*1.1||r.fe>r.dtTraGop*1.1)return null;return r}
function saveVerified(table){const rows={};for(const tr of table.querySelectorAll('tbody tr')){const r=parseRow(tr);if(r)rows[r.key]=r}if(!rows.shop1||!rows.shop2)throw new Error('Bảng chưa có đủ dữ liệu hợp lệ Hải Anh + Trực Cường');const z=obj(gv(DATA_KEY,{}));z.link7=z.link7||{};z.link2=z.link2||{};let sumTra=0,sumST=0;for(const key of ['shop1','shop2']){const r=rows[key];z.link7[key]=z.link7[key]||{};Object.assign(z.link7[key],{_SHOP_DT:r.dtSieuThi,_SHOP_HC:r.hc,_SHOP_FE:r.fe,_SHOP_TOTAL_:{tg:r.tyTrong,dt_sieu_thi:r.dtSieuThi,dt_tragop:r.dtTraGop,hc:r.hc,fe:r.fe,kredivo:r.kredivo,source:'tra-cham-v24'}});z.link2[key]=z.link2[key]||{};z.link2[key].tg=r.tyTrong;sumTra+=r.dtTraGop;sumST+=r.dtSieuThi}z.link2.total=z.link2.total||{};if(sumST>0)z.link2.total.tg=sumTra/sumST*100;sv(DATA_KEY,z);sv(LAST_KEY,Date.now());return rows}
async function runTraCham(){let st=obj(gv(STATE_KEY,{}));if(!st.run)return;try{status('Đang chọn tab Tỷ trọng trả góp...');clickIfExists('Tỷ trọng trả góp');await sleep(450);clickIfExists('Lũy kế');await sleep(650);status('Đang chọn Vùng Hà Nội+...');await selectOne('Vùng',REGION_CODE,'vung ha noi');await sleep(900);status('Đang chọn Khu vực Nam Định...');await selectOne('Khu vực',AREA_CODE,'nam dinh');await sleep(900);status('Đang để Siêu thị ở chế độ tất cả...');await clearStores();await sleep(450);status('Đang bấm Xem và chờ bảng Hải Anh + Trực Cường...');await clickXem();const table=await wait(findStoreTable,20000,350);if(!table)throw new Error('Không thấy bảng đồng thời Hải Anh + Trực Cường');await sleep(700);const rows=saveVerified(table);status(`Đã lấy đúng: Hải Anh ${rows.shop1.dtTraGop}/${rows.shop1.dtSieuThi}; Trực Cường ${rows.shop2.dtTraGop}/${rows.shop2.dtSieuThi}`,true);toast('✅ Đã tự động lấy xong dữ liệu Trả chậm',4500);sv(STATE_KEY,{run:false,done:true,back:st.back||'/dashboard/thi-dua',time:Date.now()});await sleep(1200);location.href=st.back||'/dashboard/thi-dua'}catch(e){debug('ERROR',e?.message||e);toast('⚠️ Tự lấy Trả chậm chưa thành công: '+(e?.message||e),5200);sv(STATE_KEY,{run:false,error:String(e?.message||e),back:st.back||'/dashboard/thi-dua',time:Date.now()});await sleep(1800);location.href=st.back||'/dashboard/thi-dua'}}
async function startFromAutoBI(){if(!location.pathname.includes('/dashboard/thi-dua'))return;const st=obj(gv(STATE_KEY,{}));if(st.done){dv(STATE_KEY);toast('✅ Trả chậm đã cập nhật. Mở Sức khỏe ST để kiểm tra.',4500);return}if(st.error){toast('⚠️ Trả chậm chưa tự lấy được. AutoBI chính vẫn giữ nguyên.',4500);dv(STATE_KEY);return}const last=Number(gv(LAST_KEY,0)||0);if(Date.now()-last<COOLDOWN)return;sv(STATE_KEY,{run:true,back:location.pathname+location.search+location.hash,time:Date.now()});toast('🔄 Tự động sang Báo cáo trả chậm lấy dữ liệu...',3000);await sleep(800);location.href=PATH_TC}
if(location.pathname.includes(PATH_TC))setTimeout(runTraCham,1400);else setTimeout(startFromAutoBI,4200);
})();
